[env]
platform = ch32v
framework = noneos-sdk
upload_protocol = isp
board = genericCH32X035G8U6

[env:debug]
build_flags = -DDEBUG=2 -DVERSION_MAJOR=\"255\" -DVERSION_MINOR=\"255\" -DVERSION_PATCH=\"255\"

[env:release]
